homepage:
    path:     /
    defaults: { _controller: NkStamina\NkStaminaExtension\Controller\MainController::homepageAction }


extension:
    path:     /extension/{qs}
    defaults: { _controller: NkStamina\MyExtension\Controller\MyExtensionController::indexAction }