homepage:
    path:     /
    defaults: { _controller: NkstaminaExtension\Controller\MainController::homepageAction }

init:
    path:     /extension/ExtensionInit
    defaults: { _controller: ExtensionInit\Controller\ExtensionInitController::indexAction }


extension:
    path:     /extension/{name}
    defaults: { _controller: MyExtension\Controller\MyExtensionController::indexAction }
    
